title: Marcelo Trindade
logo: /assets/img/logo.png
description: Administrador de empresas e programador, 37 anos, brasileiro.
show_downloads: false
google_analytics: G-F1WX2MGBJM
#theme: jekyll-theme-minimal
theme: jekyll-theme-midnight
plugins:
- jekyll-remote-theme
gem "github-pages", group: :jekyll_plugins
