title: Mr. Trindade, Marcelo
logo: /assets/img/gravatar.png
description: Business administrator and programmer, 37 years old, Brazilian.
show_downloads: false
google_analytics: G-CV9B770Y4Q
theme: jekyll-theme-minimal
