title: Marcelo Trindade
logo: /assets/img/gravatar.png
description: Ser administrador é muito mais do que ter uma certifição. Gerir está além do que os olhos e análises podem descrever. Gerir e administrar está na atitude independente da sua ocupação em sua organização. Liderar é um dom que vem sendo ocupado muitas vezes de forma decepcionante, mas esse é o mundo. Ser líder é trabalhar e não só delegar, e buscar por novos anseios quando aquele não mais te satisfaz, ser líder é executar e conhecer todo o seu trabalho, ser líder é mediar conflitos e não apimentá-los, ser líder é simplesmente ser líder, ser líder de si mesmo em primeiro lugar!
show_downloads: false
google_analytics: G-CV9B770Y4Q
theme: jekyll-theme-minimal
